### ISSUE TITLE
定义50 的虚拟卡,却能分配大于2个pod到一张卡上

### ISSUE THREAD

**Issue by weapons97** [Project-HAMi/volcano-vgpu-device-plugin#30]
如下定义8个pod, 每个pod 分配volcano.sh/vgpu-cores: "50", 但是进入检查pod gpu bus-id,看到6个pod都在同一个卡上
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: cnn
  template:
    metadata:
      labels:
        app: cnn
    spec:
      schedulerName: volcano
          resources:
            limits:
              # volcano.sh/vgpu-cores: "100"
              # volcano.sh/vgpu-memory: "20000"
              # volcano.sh/vgpu-number: "1"
              # nvidia.com/gpu: 1
              volcano.sh/vgpu-cores: "50"
              volcano.sh/vgpu-memory: "4544"
              volcano.sh/vgpu-number: "1"
...
```

![image](https://github.com/user-attachments/assets/ae687581-e8aa-49f9-9369-5ab74ab8a703)
